spring:
  datasource:
    url: jdbc:h2:mem:pismo
    username: sa
    password: pass
    driverClassName: org.h2.Driver

  jpa:
    properties:
      hibernate.globally_quoted_identifiers: true
      hibernate.format_sql: true
    show-sql: false
  h2:
    console.enabled: true