spring:
  datasource:
    url: jdbc:postgresql://postgresdb:5432/pismo
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true